# M5 Forecasting — ETL Pipeline: **Extract Phase**

**Project:** Retail-Demand-Forecasting
**Stage:** `01_extract` — data acquisition & exploratory profiling only
**Author:** Data Engineering / Analytics Team

---

## Purpose of this notebook

This notebook implements the **Extract** phase of an Extract–Transform–Load (ETL) pipeline for the
M5 Forecasting dataset. Its only job is to:

1. Locate the raw source files reliably, regardless of where the notebook is launched from.
2. Load the three raw M5 tables (`calendar.csv`, `sell_prices.csv`, `sales_train_validation.csv`).
3. **Profile** each dataset thoroughly (structure, types, memory, quality) so that downstream
   Transform-phase decisions are made with full knowledge of the data.
4. Document the schema, relationships, keys, and known data-quality issues.

> ⚠️ **Scope boundary — read this first**
>
> This notebook is **exploratory / diagnostic only**.
> - No missing values are imputed.
> - No columns are renamed, cast, dropped, or reshaped.
> - No merges/joins are materialized (relationships are only *inspected*).
> - No files are written back to disk.
>
> Anything that changes the data belongs in the **Transform** phase notebook
> (e.g. `notebooks/02_transform.ipynb`), not here. Keeping Extract "read-only" means we can
> re-run it safely at any time as a data-quality audit, and it gives the Transform phase a
> single, well-documented source of truth to build on.

## 1. Imports

Only lightweight, standard-library-adjacent tools are needed for extraction and profiling:
`pathlib` for filesystem-safe path resolution, `pandas`/`numpy` for tabular loading and
inspection, and `warnings` to keep the profiling output readable.

In [9]:
from pathlib import Path
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 140)
pd.set_option("display.float_format", lambda v: f"{v:,.2f}")

print(f"pandas version : {pd.__version__}")
print(f"numpy version  : {np.__version__}")
print(f"python version : {sys.version.split()[0]}")

pandas version : 3.0.5
numpy version  : 2.5.1
python version : 3.12.7

**What was done:** Imported `pathlib.Path` (for OS-independent path handling),
`pandas`/`numpy` (for data loading and profiling), and suppressed noisy runtime warnings for
cleaner output.

**Why it matters:** Using `pathlib` instead of hardcoded strings (`"C:\\Users\\..."` or
`"/home/user/..."`) is what makes this notebook portable across machines, OSes, and CI
runners — a hard requirement for anything "production-oriented."

**ETL decision influenced:** Establishes the tooling baseline for the whole Extract phase.
No heavy libraries (e.g. Dask, Spark) are introduced yet — the dataset size will be measured
later in this notebook, and *that* measurement (not assumption) will drive whether the
Transform phase needs out-of-core / chunked processing.

## 2. Locate the Project Root

The notebook lives in `Retail-Demand-Forecasting/notebooks/`. We resolve the project root
**relative to this notebook's location** rather than relying on the current working directory
(which changes depending on how Jupyter/VS Code/CI was launched). We walk upward from the
notebook's folder until we find a directory that actually contains `data/raw/`, which acts as
a lightweight "marker" for the project root.

In [10]:
def find_project_root(marker: str = "data/raw", start: Path | None = None) -> Path:
    '''Walk upward from `start` until a directory containing `marker` is found.

    This avoids hardcoding absolute paths and avoids relying on the notebook's current
    working directory, which is unreliable across editors/CI runners.
    '''
    # In a standard Jupyter session, `__vsc_ipynb_file__` / `__file__` are unavailable,
    # so we fall back to the current working directory of the running kernel, which for a
    # notebook opened at notebooks/extract.ipynb is normally the `notebooks/` folder itself.
    current = (start or Path.cwd()).resolve()

    for candidate in [current, *current.parents]:
        if (candidate / marker).exists():
            return candidate

    raise FileNotFoundError(
        f"Could not locate project root containing '{marker}'. "
        f"Started searching from: {current}"
    )


PROJECT_ROOT = find_project_root()
DATA_RAW_DIR = PROJECT_ROOT / "data" / "raw" / "m5"
SRC_DIR = PROJECT_ROOT / "src"
NOTEBOOKS_DIR = PROJECT_ROOT / "notebooks"

print(f"Project root : {PROJECT_ROOT}")
print(f"Raw data dir : {DATA_RAW_DIR}")
print(f"src dir      : {SRC_DIR}")
print(f"notebooks dir: {NOTEBOOKS_DIR}")

assert DATA_RAW_DIR.exists(), f"Raw data directory not found at {DATA_RAW_DIR}"

Project root : D:\Mlprojects\Forecasting\Retail-Demand-Forecasting
Raw data dir : D:\Mlprojects\Forecasting\Retail-Demand-Forecasting\data\raw\m5
src dir      : D:\Mlprojects\Forecasting\Retail-Demand-Forecasting\src
notebooks dir: D:\Mlprojects\Forecasting\Retail-Demand-Forecasting\notebooks

**What was done:** Implemented a marker-based project-root finder that walks up the
directory tree from the current working directory until it finds a folder containing
`data/raw/`, then derived `DATA_RAW_DIR`, `SRC_DIR`, and `NOTEBOOKS_DIR` from it.

**Why it matters:** Absolute paths (`/Users/name/...`) break the moment the repo is cloned by
someone else, moved, or run inside Docker/CI. A marker-based search means this notebook works
identically on a laptop, a teammate's machine, or a scheduled pipeline runner — with **zero**
path edits.

**ETL decision influenced:** All file I/O in this notebook — and in every downstream
Transform/Load notebook or `src/` module — should resolve paths through this same pattern
(or a shared `src/paths.py` helper built from it), rather than each notebook reinventing path
logic. This is worth promoting into `src/` once the ETL pipeline is code-ified.

## 3. Raw File Inventory

Before loading anything into memory, we confirm which files actually exist in `data/raw/`
and record their on-disk size. This catches missing/misnamed files early, with a clear error
message, instead of a confusing `pandas` traceback later.

In [11]:
EXPECTED_FILES = {
    "calendar": "calendar.csv",
    "sell_prices": "sell_prices.csv",
    "sales_train_validation": "sales_train_validation.csv",
}

inventory_rows = []
for logical_name, filename in EXPECTED_FILES.items():
    fpath = DATA_RAW_DIR / filename
    exists = fpath.exists()
    size_mb = fpath.stat().st_size / (1024 ** 2) if exists else np.nan
    inventory_rows.append(
        {"dataset": logical_name, "filename": filename, "exists": exists, "size_MB": size_mb}
    )

file_inventory = pd.DataFrame(inventory_rows)
display(file_inventory)

missing = file_inventory.loc[~file_inventory["exists"], "filename"].tolist()
if missing:
    raise FileNotFoundError(f"Missing expected raw file(s) in {DATA_RAW_DIR}: {missing}")
print("All expected raw files are present.")

                  dataset                    filename  exists  size_MB
0                calendar                calendar.csv    True     0.10
1             sell_prices             sell_prices.csv    True   193.97
2  sales_train_validation  sales_train_validation.csv    True   114.45

All expected raw files are present.

**What was done:** Verified, file-by-file, that `calendar.csv`, `sell_prices.csv`, and
`sales_train_validation.csv` exist under `data/raw/`, and recorded their raw file sizes on
disk before touching `pandas`.

**Why it matters:** A "fail fast, fail clearly" check here means a missing/misnamed file is
reported as a single readable error at the top of the pipeline, instead of an obscure
`FileNotFoundError` buried inside a `read_csv` call several cells down.

**ETL decision influenced:** This inventory step is a natural candidate for a small
`src/extract.py` utility (`validate_raw_files()`) that a future scheduled ETL job can call
before attempting extraction, so the pipeline never proceeds on incomplete input.

## 4. Load the Raw Datasets

We load all three files as-is with `pandas.read_csv`, applying **no dtype coercion, no
parsing, no renaming**. The goal of the Extract phase is to bring the data into memory
faithfully so it can be profiled; any type optimization (e.g. downcasting `d_1..d_1913` to
`int16`, converting `date` to `datetime64`) is a **Transform**-phase decision that will be
made later, informed by the profiling below.

In [12]:
calendar_df = pd.read_csv(DATA_RAW_DIR / "calendar.csv")
sell_prices_df = pd.read_csv(DATA_RAW_DIR / "sell_prices.csv")
sales_df = pd.read_csv(DATA_RAW_DIR / "sales_train_validation.csv")

raw_datasets = {
    "calendar": calendar_df,
    "sell_prices": sell_prices_df,
    "sales_train_validation": sales_df,
}

print("Loaded datasets:")
for name, df in raw_datasets.items():
    print(f"  - {name:<24} shape={df.shape}")

Loaded datasets:
  - calendar                 shape=(1969, 14)
  - sell_prices              shape=(6841121, 4)
  - sales_train_validation   shape=(30490, 1919)

**What was done:** Loaded all three CSVs into `pandas` DataFrames with default settings
(no explicit `dtype=`, no `parse_dates=`, no column filtering) and collected them into a
`raw_datasets` dict for convenient iteration in later cells.

**Why it matters:** Loading with defaults lets `pandas` show us its own type inference, which
is itself useful diagnostic information — e.g. if `pandas` infers `object` for a column we
expect to be numeric, that is a data-quality signal (mixed types, stray strings, etc.) worth
catching now rather than after a silent, incorrect Transform-phase cast.

**ETL decision influenced:** Confirms all three files load successfully and establishes the
canonical in-memory objects (`calendar_df`, `sell_prices_df`, `sales_df`) referenced throughout
the rest of this notebook and by the Transform phase.

## 5. Profiling Utilities

To apply an **identical** profiling routine to all three datasets (head, shape, columns,
`info()`, `describe()`, memory usage, missing values, duplicates), we define one reusable
function instead of repeating the same eight cells three times. This keeps the notebook
consistent and makes it trivial to profile a fourth dataset later (e.g. `sales_train_evaluation.csv`)
by calling the same function.

In [13]:
def profile_dataset(df: pd.DataFrame, name: str, n_head: int = 5) -> None:
    '''Print a standard exploratory profile for a raw DataFrame.'''
    print("=" * 90)
    print(f"DATASET: {name}")
    print("=" * 90)

    print(f"\n--- shape ---\n{df.shape[0]:,} rows x {df.shape[1]:,} columns")

    print(f"\n--- columns ---\n{list(df.columns)}")

    print(f"\n--- head({n_head}) ---")
    display(df.head(n_head))

    print("\n--- info() ---")
    df.info(memory_usage="deep")

    print("\n--- describe(include='all').T ---")
    display(df.describe(include="all").T)

    mem_deep_mb = df.memory_usage(deep=True).sum() / (1024 ** 2)
    print(f"\n--- memory usage (deep) ---\n{mem_deep_mb:,.2f} MB total")
    display((df.memory_usage(deep=True) / (1024 ** 2)).rename("MB").to_frame())

    print("\n--- missing values ---")
    missing_counts = df.isna().sum()
    missing_pct = (missing_counts / len(df) * 100).round(2)
    missing_report = (
        pd.DataFrame({"missing_count": missing_counts, "missing_pct": missing_pct})
        .query("missing_count > 0")
        .sort_values("missing_count", ascending=False)
    )
    if missing_report.empty:
        print("No missing values detected in any column.")
    else:
        display(missing_report)

    print("\n--- duplicate rows ---")
    n_dupes = df.duplicated().sum()
    print(f"{n_dupes:,} fully duplicated row(s) out of {len(df):,} ({n_dupes / len(df) * 100:.4f}%)")

**What was done:** Defined `profile_dataset()`, a single function that prints shape,
columns, `head()`, `info()`, `describe()`, per-column and total memory usage, a missing-value
report (count + percentage, non-empty columns only), and a full-row duplicate count.

**Why it matters:** Centralizing profiling logic prevents copy-paste drift between the three
dataset sections below (e.g. forgetting `deep=True` on one `memory_usage()` call), and makes
the notebook's diagnostic behavior easy to unit-test later if it's promoted into `src/`.

**ETL decision influenced:** This function is a strong candidate for `src/profiling.py` so the
same audit can be re-run automatically every time new raw data lands (e.g. a new M5-style
weekly refresh), turning this notebook's logic into a repeatable data-quality gate.

## 6. Dataset Profile — `calendar.csv`

### Column reference

| Column | Meaning |
|---|---|
| `date` | Calendar date in `YYYY-MM-DD` format. |
| `wm_yr_wk` | Walmart internal *year-week* identifier (e.g. `11101`). Links to `sell_prices.wm_yr_wk`. |
| `weekday` | Day name (`Monday`, `Tuesday`, …). |
| `wday` | Numeric weekday code (1–7); Walmart's fiscal week starts on Saturday. |
| `month` | Calendar month (1–12). |
| `year` | Calendar year. |
| `d` | The **day key** (`d_1`, `d_2`, …, `d_1913+`) — this is the critical join column, since `sales_train_validation.csv` stores one column per `d_i` instead of one row per day. |
| `event_name_1`, `event_type_1` | Name/type of a primary special event on that date (e.g. `SuperBowl` / `Sporting`), if any. |
| `event_name_2`, `event_type_2` | Name/type of a secondary event, for days with two overlapping events. |
| `snap_CA`, `snap_TX`, `snap_WI` | Binary flag (0/1): whether SNAP (food-assistance) purchases were allowed that day, per state. |

`calendar` is the **time backbone** of the whole dataset: it is the only table with one row
per calendar day, and it is what lets the wide `d_i` sales columns be reshaped into an actual
time series later.

In [14]:
profile_dataset(calendar_df, "calendar")

==========================================================================================
DATASET: calendar
==========================================================================================

--- shape ---
1,969 rows x 14 columns

--- columns ---
['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

--- head(5) ---

         date  wm_yr_wk    weekday  wday  month  year    d event_name_1 event_type_1 event_name_2 event_type_2  snap_CA  snap_TX  snap_WI
0  2011-01-29     11101   Saturday     1      1  2011  d_1          NaN          NaN          NaN          NaN        0        0        0
1  2011-01-30     11101     Sunday     2      1  2011  d_2          NaN          NaN          NaN          NaN        0        0        0
2  2011-01-31     11101     Monday     3      1  2011  d_3          NaN          NaN          NaN          NaN        0        0        0
3  2011-02-01     11101    Tuesday     4      2  2011  d_4          NaN          NaN          NaN          NaN        1        1        0
4  2011-02-02     11101  Wednesday     5      2  2011  d_5          NaN          NaN          NaN          NaN        1        0        1

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 688.8 KB

--- describe(include='all').T ---

                count unique           top freq      mean    std       min       25%       50%       75%       max
date             1969   1969    2011-01-29    1       NaN    NaN       NaN       NaN       NaN       NaN       NaN
wm_yr_wk     1,969.00    NaN           NaN  NaN 11,347.09 155.28 11,101.00 11,219.00 11,337.00 11,502.00 11,621.00
weekday          1969      7      Saturday  282       NaN    NaN       NaN       NaN       NaN       NaN       NaN
wday         1,969.00    NaN           NaN  NaN      4.00   2.00      1.00      2.00      4.00      6.00      7.00
month        1,969.00    NaN           NaN  NaN      6.33   3.42      1.00      3.00      6.00      9.00     12.00
year         1,969.00    NaN           NaN  NaN  2,013.29   1.58  2,011.00  2,012.00  2,013.00  2,015.00  2,016.00
d                1969   1969           d_1    1       NaN    NaN       NaN       NaN       NaN       NaN       NaN
event_name_1      162     30     SuperBowl    6       NaN    NaN       NaN       NaN       NaN       NaN       NaN
event_type_1      162      4     Religious   55       NaN    NaN       NaN       NaN       NaN       NaN       NaN
event_name_2        5      4  Father's day    2       NaN    NaN       NaN       NaN       NaN       NaN       NaN
event_type_2        5      2      Cultural    4       NaN    NaN       NaN       NaN       NaN       NaN       NaN
snap_CA      1,969.00    NaN           NaN  NaN      0.33   0.47      0.00      0.00      0.00      1.00      1.00
snap_TX      1,969.00    NaN           NaN  NaN      0.33   0.47      0.00      0.00      0.00      1.00      1.00
snap_WI      1,969.00    NaN           NaN  NaN      0.33   0.47      0.00      0.00      0.00      1.00      1.00

--- memory usage (deep) ---
0.67 MB total

               MB
Index        0.00
date         0.11
wm_yr_wk     0.02
weekday      0.11
wday         0.02
month        0.02
year         0.02
d            0.10
event_name_1 0.06
event_type_1 0.06
event_name_2 0.06
event_type_2 0.06
snap_CA      0.02
snap_TX      0.02
snap_WI      0.02

--- missing values ---

              missing_count  missing_pct
event_type_2           1964        99.75
event_name_2           1964        99.75
event_type_1           1807        91.77
event_name_1           1807        91.77

--- duplicate rows ---
0 fully duplicated row(s) out of 1,969 (0.0000%)

**What was done:** Ran the full profiling routine on `calendar_df`.

**Why it matters:** `calendar` is small but structurally critical — every downstream
time-based feature (day of week, month, SNAP eligibility, holiday proximity) originates here.
Confirming its `d` values are unique and sequential, and understanding which `event_*` /
`snap_*` columns carry nulls, is essential before it can safely be used as a join key.

**ETL decision influenced:** The extent of missing values in `event_name_1/2` and
`event_type_1/2` (expected to be high, since most days have no event) tells the Transform
phase these are **legitimately sparse categorical flags**, not a data-quality defect — they
should be filled with an explicit `"no_event"` sentinel in Transform, *not* dropped.

## 7. Dataset Profile — `sell_prices.csv`

### Column reference

| Column | Meaning |
|---|---|
| `store_id` | Store identifier, formatted `{STATE}_{store_number}` (e.g. `CA_1`). |
| `item_id` | Product identifier, formatted `{DEPT}_{item_number}` (e.g. `HOBBIES_1_001`). |
| `wm_yr_wk` | Year-week identifier — joins back to `calendar.wm_yr_wk` (many `date` rows share one `wm_yr_wk`, since prices are **weekly**, not daily). |
| `sell_price` | Average selling price of the item at that store, for that week, in (unspecified) currency units. |

`sell_prices` is a **fact table at weekly grain** — one row per (store, item, week) — which is
coarser than the daily grain of `sales_train_validation`. That grain mismatch is a key join
consideration for the Transform phase.

In [15]:
profile_dataset(sell_prices_df, "sell_prices")

==========================================================================================
DATASET: sell_prices
==========================================================================================

--- shape ---
6,841,121 rows x 4 columns

--- columns ---
['store_id', 'item_id', 'wm_yr_wk', 'sell_price']

--- head(5) ---

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    str
 1   item_id     str
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 853.1 MB

--- describe(include='all').T ---

                  count unique            top    freq      mean    std       min       25%       50%       75%       max
store_id        6841121     10           TX_2  701214       NaN    NaN       NaN       NaN       NaN       NaN       NaN
item_id         6841121   3049  HOBBIES_1_010    2820       NaN    NaN       NaN       NaN       NaN       NaN       NaN
wm_yr_wk   6,841,121.00    NaN            NaN     NaN 11,382.94 148.61 11,101.00 11,247.00 11,411.00 11,517.00 11,621.00
sell_price 6,841,121.00    NaN            NaN     NaN      4.41   3.41      0.01      2.18      3.47      5.84    107.32

--- memory usage (deep) ---
853.13 MB total

               MB
Index        0.00
store_id   345.78
item_id    402.96
wm_yr_wk    52.19
sell_price  52.19

--- missing values ---
No missing values detected in any column.

--- duplicate rows ---
0 fully duplicated row(s) out of 6,841,121 (0.0000%)

**What was done:** Ran the full profiling routine on `sell_prices_df`.

**Why it matters:** This table is typically the **largest** of the three by row count (one row
per store × item × week, across ~5 years), so its memory footprint and dtype choices matter
disproportionately for pipeline performance. Confirming whether `sell_price` has nulls or
negative/zero values here (rather than assuming) determines whether "missing price" is a real
phenomenon in this dataset (e.g. item not yet sold) or a data artifact.

**ETL decision influenced:** Because `sell_prices` is keyed at `(store_id, item_id, wm_yr_wk)`
— **weekly**, not daily — any join into the daily sales/calendar data will necessarily
broadcast one price across ~7 days. That's a modeling assumption the Transform phase must
apply deliberately, not something `pandas` will warn about automatically.

## 8. Dataset Profile — `sales_train_validation.csv`

### Column reference

| Column | Meaning |
|---|---|
| `id` | Unique row identifier, formatted `{item_id}_{store_id}_validation`. One row = one (item, store) time series. |
| `item_id` | Product identifier (same domain as in `sell_prices`). |
| `dept_id` | Department the item belongs to (e.g. `HOBBIES_1`). |
| `cat_id` | Top-level category (`HOBBIES`, `HOUSEHOLD`, `FOODS`). |
| `store_id` | Store identifier (same domain as in `sell_prices`). |
| `state_id` | US state the store is located in (`CA`, `TX`, `WI`) — functionally dependent on `store_id`. |
| `d_1`, `d_2`, …, `d_n` | **Units sold** on that day, one column per day. Column name `d_i` joins to `calendar.d`. This is the dataset's defining "wide" structure. |

This table is the **primary fact table** of the whole project: it is what we are ultimately
trying to forecast. Every other table exists to enrich it (with time attributes or price
attributes).

In [16]:
profile_dataset(sales_df, "sales_train_validation")

==========================================================================================
DATASET: sales_train_validation
==========================================================================================

--- shape ---
30,490 rows x 1,919 columns

--- columns ---
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9', 'd_10', 'd_11', 'd_12', 'd_13', 'd_14', 'd_15', 'd_16', 'd_17', 'd_18', 'd_19', 'd_20', 'd_21', 'd_22', 'd_23', 'd_24', 'd_25', 'd_26', 'd_27', 'd_28', 'd_29', 'd_30', 'd_31', 'd_32', 'd_33', 'd_34', 'd_35', 'd_36', 'd_37', 'd_38', 'd_39', 'd_40', 'd_41', 'd_42', 'd_43', 'd_44', 'd_45', 'd_46', 'd_47', 'd_48', 'd_49', 'd_50', 'd_51', 'd_52', 'd_53', 'd_54', 'd_55', 'd_56', 'd_57', 'd_58', 'd_59', 'd_60', 'd_61', 'd_62', 'd_63', 'd_64', 'd_65', 'd_66', 'd_67', 'd_68', 'd_69', 'd_70', 'd_71', 'd_72', 'd_73', 'd_74', 'd_75', 'd_76', 'd_77', 'd_78', 'd_79', 'd_80', 'd_81', 'd_82', 'd_83', 'd_84', 'd_85', 'd_86', 'd_87', 'd_88', 'd_89', 'd_90', 'd_91', 'd_92', 'd_93', 'd_94', 'd_95', 'd_96', 'd_97', 'd_98', 'd_99', 'd_100', 'd_101', 'd_102', 'd_103', 'd_104', 'd_105', 'd_106', 'd_107', 'd_108', 'd_109', 'd_110', 'd_111', 'd_112', 'd_113', 'd_114', 'd_115', 'd_116', 'd_117', 'd_118', 'd_119', 'd_120', 'd_121', 'd_122', 'd_123', 'd_124', 'd_125', 'd_126', 'd_127', 'd_128', 'd_129', 'd_130', 'd_131', 'd_132', 'd_133', 'd_134', 'd_135', 'd_136', 'd_137', 'd_138', 'd_139', 'd_140', 'd_141', 'd_142', 'd_143', 'd_144', 'd_145', 'd_146', 'd_147', 'd_148', 'd_149', 'd_150', 'd_151', 'd_152', 'd_153', 'd_154', 'd_155', 'd_156', 'd_157', 'd_158', 'd_159', 'd_160', 'd_161', 'd_162', 'd_163', 'd_164', 'd_165', 'd_166', 'd_167', 'd_168', 'd_169', 'd_170', 'd_171', 'd_172', 'd_173', 'd_174', 'd_175', 'd_176', 'd_177', 'd_178', 'd_179', 'd_180', 'd_181', 'd_182', 'd_183', 'd_184', 'd_185', 'd_186', 'd_187', 'd_188', 'd_189', 'd_190', 'd_191', 'd_192', 'd_193', 'd_194', 'd_195', 'd_196', 'd_197', 'd_198', 'd_199', 'd_200', 'd_201', 'd_202', 'd_203', 'd_204', 'd_205', 'd_206', 'd_207', 'd_208', 'd_209', 'd_210', 'd_211', 'd_212', 'd_213', 'd_214', 'd_215', 'd_216', 'd_217', 'd_218', 'd_219', 'd_220', 'd_221', 'd_222', 'd_223', 'd_224', 'd_225', 'd_226', 'd_227', 'd_228', 'd_229', 'd_230', 'd_231', 'd_232', 'd_233', 'd_234', 'd_235', 'd_236', 'd_237', 'd_238', 'd_239', 'd_240', 'd_241', 'd_242', 'd_243', 'd_244', 'd_245', 'd_246', 'd_247', 'd_248', 'd_249', 'd_250', 'd_251', 'd_252', 'd_253', 'd_254', 'd_255', 'd_256', 'd_257', 'd_258', 'd_259', 'd_260', 'd_261', 'd_262', 'd_263', 'd_264', 'd_265', 'd_266', 'd_267', 'd_268', 'd_269', 'd_270', 'd_271', 'd_272', 'd_273', 'd_274', 'd_275', 'd_276', 'd_277', 'd_278', 'd_279', 'd_280', 'd_281', 'd_282', 'd_283', 'd_284', 'd_285', 'd_286', 'd_287', 'd_288', 'd_289', 'd_290', 'd_291', 'd_292', 'd_293', 'd_294', 'd_295', 'd_296', 'd_297', 'd_298', 'd_299', 'd_300', 'd_301', 'd_302', 'd_303', 'd_304', 'd_305', 'd_306', 'd_307', 'd_308', 'd_309', 'd_310', 'd_311', 'd_312', 'd_313', 'd_314', 'd_315', 'd_316', 'd_317', 'd_318', 'd_319', 'd_320', 'd_321', 'd_322', 'd_323', 'd_324', 'd_325', 'd_326', 'd_327', 'd_328', 'd_329', 'd_330', 'd_331', 'd_332', 'd_333', 'd_334', 'd_335', 'd_336', 'd_337', 'd_338', 'd_339', 'd_340', 'd_341', 'd_342', 'd_343', 'd_344', 'd_345', 'd_346', 'd_347', 'd_348', 'd_349', 'd_350', 'd_351', 'd_352', 'd_353', 'd_354', 'd_355', 'd_356', 'd_357', 'd_358', 'd_359', 'd_360', 'd_361', 'd_362', 'd_363', 'd_364', 'd_365', 'd_366', 'd_367', 'd_368', 'd_369', 'd_370', 'd_371', 'd_372', 'd_373', 'd_374', 'd_375', 'd_376', 'd_377', 'd_378', 'd_379', 'd_380', 'd_381', 'd_382', 'd_383', 'd_384', 'd_385', 'd_386', 'd_387', 'd_388', 'd_389', 'd_390', 'd_391', 'd_392', 'd_393', 'd_394', 'd_395', 'd_396', 'd_397', 'd_398', 'd_399', 'd_400', 'd_401', 'd_402', 'd_403', 'd_404', 'd_405', 'd_406', 'd_407', 'd_408', 'd_409', 'd_410', 'd_411', 'd_412', 'd_413', 'd_414', 'd_415', 'd_416', 'd_417', 'd_418', 'd_419', 'd_420', 'd_421', 'd_422', 'd_423', 'd_424', 'd_425', 'd_426', 'd_427', 'd_428', 'd_429', 'd_430', 'd_431', 'd_432', 'd_433', 'd_434', 'd_435', 'd_436', 'd_437', 'd_438', 'd_439', 'd_440', 'd_441', 'd_442', 'd_443', 'd_444', 'd_445', 'd_446', 'd_447', 'd_448', 'd_449', 'd_450', 'd_451', 'd_452', 'd_453', 'd_454', 'd_455', 'd_456', 'd_457', 'd_458', 'd_459', 'd_460', 'd_461', 'd_462', 'd_463', 'd_464', 'd_465', 'd_466', 'd_467', 'd_468', 'd_469', 'd_470', 'd_471', 'd_472', 'd_473', 'd_474', 'd_475', 'd_476', 'd_477', 'd_478', 'd_479', 'd_480', 'd_481', 'd_482', 'd_483', 'd_484', 'd_485', 'd_486', 'd_487', 'd_488', 'd_489', 'd_490', 'd_491', 'd_492', 'd_493', 'd_494', 'd_495', 'd_496', 'd_497', 'd_498', 'd_499', 'd_500', 'd_501', 'd_502', 'd_503', 'd_504', 'd_505', 'd_506', 'd_507', 'd_508', 'd_509', 'd_510', 'd_511', 'd_512', 'd_513', 'd_514', 'd_515', 'd_516', 'd_517', 'd_518', 'd_519', 'd_520', 'd_521', 'd_522', 'd_523', 'd_524', 'd_525', 'd_526', 'd_527', 'd_528', 'd_529', 'd_530', 'd_531', 'd_532', 'd_533', 'd_534', 'd_535', 'd_536', 'd_537', 'd_538', 'd_539', 'd_540', 'd_541', 'd_542', 'd_543', 'd_544', 'd_545', 'd_546', 'd_547', 'd_548', 'd_549', 'd_550', 'd_551', 'd_552', 'd_553', 'd_554', 'd_555', 'd_556', 'd_557', 'd_558', 'd_559', 'd_560', 'd_561', 'd_562', 'd_563', 'd_564', 'd_565', 'd_566', 'd_567', 'd_568', 'd_569', 'd_570', 'd_571', 'd_572', 'd_573', 'd_574', 'd_575', 'd_576', 'd_577', 'd_578', 'd_579', 'd_580', 'd_581', 'd_582', 'd_583', 'd_584', 'd_585', 'd_586', 'd_587', 'd_588', 'd_589', 'd_590', 'd_591', 'd_592', 'd_593', 'd_594', 'd_595', 'd_596', 'd_597', 'd_598', 'd_599', 'd_600', 'd_601', 'd_602', 'd_603', 'd_604', 'd_605', 'd_606', 'd_607', 'd_608', 'd_609', 'd_610', 'd_611', 'd_612', 'd_613', 'd_614', 'd_615', 'd_616', 'd_617', 'd_618', 'd_619', 'd_620', 'd_621', 'd_622', 'd_623', 'd_624', 'd_625', 'd_626', 'd_627', 'd_628', 'd_629', 'd_630', 'd_631', 'd_632', 'd_633', 'd_634', 'd_635', 'd_636', 'd_637', 'd_638', 'd_639', 'd_640', 'd_641', 'd_642', 'd_643', 'd_644', 'd_645', 'd_646', 'd_647', 'd_648', 'd_649', 'd_650', 'd_651', 'd_652', 'd_653', 'd_654', 'd_655', 'd_656', 'd_657', 'd_658', 'd_659', 'd_660', 'd_661', 'd_662', 'd_663', 'd_664', 'd_665', 'd_666', 'd_667', 'd_668', 'd_669', 'd_670', 'd_671', 'd_672', 'd_673', 'd_674', 'd_675', 'd_676', 'd_677', 'd_678', 'd_679', 'd_680', 'd_681', 'd_682', 'd_683', 'd_684', 'd_685', 'd_686', 'd_687', 'd_688', 'd_689', 'd_690', 'd_691', 'd_692', 'd_693', 'd_694', 'd_695', 'd_696', 'd_697', 'd_698', 'd_699', 'd_700', 'd_701', 'd_702', 'd_703', 'd_704', 'd_705', 'd_706', 'd_707', 'd_708', 'd_709', 'd_710', 'd_711', 'd_712', 'd_713', 'd_714', 'd_715', 'd_716', 'd_717', 'd_718', 'd_719', 'd_720', 'd_721', 'd_722', 'd_723', 'd_724', 'd_725', 'd_726', 'd_727', 'd_728', 'd_729', 'd_730', 'd_731', 'd_732', 'd_733', 'd_734', 'd_735', 'd_736', 'd_737', 'd_738', 'd_739', 'd_740', 'd_741', 'd_742', 'd_743', 'd_744', 'd_745', 'd_746', 'd_747', 'd_748', 'd_749', 'd_750', 'd_751', 'd_752', 'd_753', 'd_754', 'd_755', 'd_756', 'd_757', 'd_758', 'd_759', 'd_760', 'd_761', 'd_762', 'd_763', 'd_764', 'd_765', 'd_766', 'd_767', 'd_768', 'd_769', 'd_770', 'd_771', 'd_772', 'd_773', 'd_774', 'd_775', 'd_776', 'd_777', 'd_778', 'd_779', 'd_780', 'd_781', 'd_782', 'd_783', 'd_784', 'd_785', 'd_786', 'd_787', 'd_788', 'd_789', 'd_790', 'd_791', 'd_792', 'd_793', 'd_794', 'd_795', 'd_796', 'd_797', 'd_798', 'd_799', 'd_800', 'd_801', 'd_802', 'd_803', 'd_804', 'd_805', 'd_806', 'd_807', 'd_808', 'd_809', 'd_810', 'd_811', 'd_812', 'd_813', 'd_814', 'd_815', 'd_816', 'd_817', 'd_818', 'd_819', 'd_820', 'd_821', 'd_822', 'd_823', 'd_824', 'd_825', 'd_826', 'd_827', 'd_828', 'd_829', 'd_830', 'd_831', 'd_832', 'd_833', 'd_834', 'd_835', 'd_836', 'd_837', 'd_838', 'd_839', 'd_840', 'd_841', 'd_842', 'd_843', 'd_844', 'd_845', 'd_846', 'd_847', 'd_848', 'd_849', 'd_850', 'd_851', 'd_852', 'd_853', 'd_854', 'd_855', 'd_856', 'd_857', 'd_858', 'd_859', 'd_860', 'd_861', 'd_862', 'd_863', 'd_864', 'd_865', 'd_866', 'd_867', 'd_868', 'd_869', 'd_870', 'd_871', 'd_872', 'd_873', 'd_874', 'd_875', 'd_876', 'd_877', 'd_878', 'd_879', 'd_880', 'd_881', 'd_882', 'd_883', 'd_884', 'd_885', 'd_886', 'd_887', 'd_888', 'd_889', 'd_890', 'd_891', 'd_892', 'd_893', 'd_894', 'd_895', 'd_896', 'd_897', 'd_898', 'd_899', 'd_900', 'd_901', 'd_902', 'd_903', 'd_904', 'd_905', 'd_906', 'd_907', 'd_908', 'd_909', 'd_910', 'd_911', 'd_912', 'd_913', 'd_914', 'd_915', 'd_916', 'd_917', 'd_918', 'd_919', 'd_920', 'd_921', 'd_922', 'd_923', 'd_924', 'd_925', 'd_926', 'd_927', 'd_928', 'd_929', 'd_930', 'd_931', 'd_932', 'd_933', 'd_934', 'd_935', 'd_936', 'd_937', 'd_938', 'd_939', 'd_940', 'd_941', 'd_942', 'd_943', 'd_944', 'd_945', 'd_946', 'd_947', 'd_948', 'd_949', 'd_950', 'd_951', 'd_952', 'd_953', 'd_954', 'd_955', 'd_956', 'd_957', 'd_958', 'd_959', 'd_960', 'd_961', 'd_962', 'd_963', 'd_964', 'd_965', 'd_966', 'd_967', 'd_968', 'd_969', 'd_970', 'd_971', 'd_972', 'd_973', 'd_974', 'd_975', 'd_976', 'd_977', 'd_978', 'd_979', 'd_980', 'd_981', 'd_982', 'd_983', 'd_984', 'd_985', 'd_986', 'd_987', 'd_988', 'd_989', 'd_990', 'd_991', 'd_992', 'd_993', 'd_994', 'd_995', 'd_996', 'd_997', 'd_998', 'd_999', 'd_1000', 'd_1001', 'd_1002', 'd_1003', 'd_1004', 'd_1005', 'd_1006', 'd_1007', 'd_1008', 'd_1009', 'd_1010', 'd_1011', 'd_1012', 'd_1013', 'd_1014', 'd_1015', 'd_1016', 'd_1017', 'd_1018', 'd_1019', 'd_1020', 'd_1021', 'd_1022', 'd_1023', 'd_1024', 'd_1025', 'd_1026', 'd_1027', 'd_1028', 'd_1029', 'd_1030', 'd_1031', 'd_1032', 'd_1033', 'd_1034', 'd_1035', 'd_1036', 'd_1037', 'd_1038', 'd_1039', 'd_1040', 'd_1041', 'd_1042', 'd_1043', 'd_1044', 'd_1045', 'd_1046', 'd_1047', 'd_1048', 'd_1049', 'd_1050', 'd_1051', 'd_1052', 'd_1053', 'd_1054', 'd_1055', 'd_1056', 'd_1057', 'd_1058', 'd_1059', 'd_1060', 'd_1061', 'd_1062', 'd_1063', 'd_1064', 'd_1065', 'd_1066', 'd_1067', 'd_1068', 'd_1069', 'd_1070', 'd_1071', 'd_1072', 'd_1073', 'd_1074', 'd_1075', 'd_1076', 'd_1077', 'd_1078', 'd_1079', 'd_1080', 'd_1081', 'd_1082', 'd_1083', 'd_1084', 'd_1085', 'd_1086', 'd_1087', 'd_1088', 'd_1089', 'd_1090', 'd_1091', 'd_1092', 'd_1093', 'd_1094', 'd_1095', 'd_1096', 'd_1097', 'd_1098', 'd_1099', 'd_1100', 'd_1101', 'd_1102', 'd_1103', 'd_1104', 'd_1105', 'd_1106', 'd_1107', 'd_1108', 'd_1109', 'd_1110', 'd_1111', 'd_1112', 'd_1113', 'd_1114', 'd_1115', 'd_1116', 'd_1117', 'd_1118', 'd_1119', 'd_1120', 'd_1121', 'd_1122', 'd_1123', 'd_1124', 'd_1125', 'd_1126', 'd_1127', 'd_1128', 'd_1129', 'd_1130', 'd_1131', 'd_1132', 'd_1133', 'd_1134', 'd_1135', 'd_1136', 'd_1137', 'd_1138', 'd_1139', 'd_1140', 'd_1141', 'd_1142', 'd_1143', 'd_1144', 'd_1145', 'd_1146', 'd_1147', 'd_1148', 'd_1149', 'd_1150', 'd_1151', 'd_1152', 'd_1153', 'd_1154', 'd_1155', 'd_1156', 'd_1157', 'd_1158', 'd_1159', 'd_1160', 'd_1161', 'd_1162', 'd_1163', 'd_1164', 'd_1165', 'd_1166', 'd_1167', 'd_1168', 'd_1169', 'd_1170', 'd_1171', 'd_1172', 'd_1173', 'd_1174', 'd_1175', 'd_1176', 'd_1177', 'd_1178', 'd_1179', 'd_1180', 'd_1181', 'd_1182', 'd_1183', 'd_1184', 'd_1185', 'd_1186', 'd_1187', 'd_1188', 'd_1189', 'd_1190', 'd_1191', 'd_1192', 'd_1193', 'd_1194', 'd_1195', 'd_1196', 'd_1197', 'd_1198', 'd_1199', 'd_1200', 'd_1201', 'd_1202', 'd_1203', 'd_1204', 'd_1205', 'd_1206', 'd_1207', 'd_1208', 'd_1209', 'd_1210', 'd_1211', 'd_1212', 'd_1213', 'd_1214', 'd_1215', 'd_1216', 'd_1217', 'd_1218', 'd_1219', 'd_1220', 'd_1221', 'd_1222', 'd_1223', 'd_1224', 'd_1225', 'd_1226', 'd_1227', 'd_1228', 'd_1229', 'd_1230', 'd_1231', 'd_1232', 'd_1233', 'd_1234', 'd_1235', 'd_1236', 'd_1237', 'd_1238', 'd_1239', 'd_1240', 'd_1241', 'd_1242', 'd_1243', 'd_1244', 'd_1245', 'd_1246', 'd_1247', 'd_1248', 'd_1249', 'd_1250', 'd_1251', 'd_1252', 'd_1253', 'd_1254', 'd_1255', 'd_1256', 'd_1257', 'd_1258', 'd_1259', 'd_1260', 'd_1261', 'd_1262', 'd_1263', 'd_1264', 'd_1265', 'd_1266', 'd_1267', 'd_1268', 'd_1269', 'd_1270', 'd_1271', 'd_1272', 'd_1273', 'd_1274', 'd_1275', 'd_1276', 'd_1277', 'd_1278', 'd_1279', 'd_1280', 'd_1281', 'd_1282', 'd_1283', 'd_1284', 'd_1285', 'd_1286', 'd_1287', 'd_1288', 'd_1289', 'd_1290', 'd_1291', 'd_1292', 'd_1293', 'd_1294', 'd_1295', 'd_1296', 'd_1297', 'd_1298', 'd_1299', 'd_1300', 'd_1301', 'd_1302', 'd_1303', 'd_1304', 'd_1305', 'd_1306', 'd_1307', 'd_1308', 'd_1309', 'd_1310', 'd_1311', 'd_1312', 'd_1313', 'd_1314', 'd_1315', 'd_1316', 'd_1317', 'd_1318', 'd_1319', 'd_1320', 'd_1321', 'd_1322', 'd_1323', 'd_1324', 'd_1325', 'd_1326', 'd_1327', 'd_1328', 'd_1329', 'd_1330', 'd_1331', 'd_1332', 'd_1333', 'd_1334', 'd_1335', 'd_1336', 'd_1337', 'd_1338', 'd_1339', 'd_1340', 'd_1341', 'd_1342', 'd_1343', 'd_1344', 'd_1345', 'd_1346', 'd_1347', 'd_1348', 'd_1349', 'd_1350', 'd_1351', 'd_1352', 'd_1353', 'd_1354', 'd_1355', 'd_1356', 'd_1357', 'd_1358', 'd_1359', 'd_1360', 'd_1361', 'd_1362', 'd_1363', 'd_1364', 'd_1365', 'd_1366', 'd_1367', 'd_1368', 'd_1369', 'd_1370', 'd_1371', 'd_1372', 'd_1373', 'd_1374', 'd_1375', 'd_1376', 'd_1377', 'd_1378', 'd_1379', 'd_1380', 'd_1381', 'd_1382', 'd_1383', 'd_1384', 'd_1385', 'd_1386', 'd_1387', 'd_1388', 'd_1389', 'd_1390', 'd_1391', 'd_1392', 'd_1393', 'd_1394', 'd_1395', 'd_1396', 'd_1397', 'd_1398', 'd_1399', 'd_1400', 'd_1401', 'd_1402', 'd_1403', 'd_1404', 'd_1405', 'd_1406', 'd_1407', 'd_1408', 'd_1409', 'd_1410', 'd_1411', 'd_1412', 'd_1413', 'd_1414', 'd_1415', 'd_1416', 'd_1417', 'd_1418', 'd_1419', 'd_1420', 'd_1421', 'd_1422', 'd_1423', 'd_1424', 'd_1425', 'd_1426', 'd_1427', 'd_1428', 'd_1429', 'd_1430', 'd_1431', 'd_1432', 'd_1433', 'd_1434', 'd_1435', 'd_1436', 'd_1437', 'd_1438', 'd_1439', 'd_1440', 'd_1441', 'd_1442', 'd_1443', 'd_1444', 'd_1445', 'd_1446', 'd_1447', 'd_1448', 'd_1449', 'd_1450', 'd_1451', 'd_1452', 'd_1453', 'd_1454', 'd_1455', 'd_1456', 'd_1457', 'd_1458', 'd_1459', 'd_1460', 'd_1461', 'd_1462', 'd_1463', 'd_1464', 'd_1465', 'd_1466', 'd_1467', 'd_1468', 'd_1469', 'd_1470', 'd_1471', 'd_1472', 'd_1473', 'd_1474', 'd_1475', 'd_1476', 'd_1477', 'd_1478', 'd_1479', 'd_1480', 'd_1481', 'd_1482', 'd_1483', 'd_1484', 'd_1485', 'd_1486', 'd_1487', 'd_1488', 'd_1489', 'd_1490', 'd_1491', 'd_1492', 'd_1493', 'd_1494', 'd_1495', 'd_1496', 'd_1497', 'd_1498', 'd_1499', 'd_1500', 'd_1501', 'd_1502', 'd_1503', 'd_1504', 'd_1505', 'd_1506', 'd_1507', 'd_1508', 'd_1509', 'd_1510', 'd_1511', 'd_1512', 'd_1513', 'd_1514', 'd_1515', 'd_1516', 'd_1517', 'd_1518', 'd_1519', 'd_1520', 'd_1521', 'd_1522', 'd_1523', 'd_1524', 'd_1525', 'd_1526', 'd_1527', 'd_1528', 'd_1529', 'd_1530', 'd_1531', 'd_1532', 'd_1533', 'd_1534', 'd_1535', 'd_1536', 'd_1537', 'd_1538', 'd_1539', 'd_1540', 'd_1541', 'd_1542', 'd_1543', 'd_1544', 'd_1545', 'd_1546', 'd_1547', 'd_1548', 'd_1549', 'd_1550', 'd_1551', 'd_1552', 'd_1553', 'd_1554', 'd_1555', 'd_1556', 'd_1557', 'd_1558', 'd_1559', 'd_1560', 'd_1561', 'd_1562', 'd_1563', 'd_1564', 'd_1565', 'd_1566', 'd_1567', 'd_1568', 'd_1569', 'd_1570', 'd_1571', 'd_1572', 'd_1573', 'd_1574', 'd_1575', 'd_1576', 'd_1577', 'd_1578', 'd_1579', 'd_1580', 'd_1581', 'd_1582', 'd_1583', 'd_1584', 'd_1585', 'd_1586', 'd_1587', 'd_1588', 'd_1589', 'd_1590', 'd_1591', 'd_1592', 'd_1593', 'd_1594', 'd_1595', 'd_1596', 'd_1597', 'd_1598', 'd_1599', 'd_1600', 'd_1601', 'd_1602', 'd_1603', 'd_1604', 'd_1605', 'd_1606', 'd_1607', 'd_1608', 'd_1609', 'd_1610', 'd_1611', 'd_1612', 'd_1613', 'd_1614', 'd_1615', 'd_1616', 'd_1617', 'd_1618', 'd_1619', 'd_1620', 'd_1621', 'd_1622', 'd_1623', 'd_1624', 'd_1625', 'd_1626', 'd_1627', 'd_1628', 'd_1629', 'd_1630', 'd_1631', 'd_1632', 'd_1633', 'd_1634', 'd_1635', 'd_1636', 'd_1637', 'd_1638', 'd_1639', 'd_1640', 'd_1641', 'd_1642', 'd_1643', 'd_1644', 'd_1645', 'd_1646', 'd_1647', 'd_1648', 'd_1649', 'd_1650', 'd_1651', 'd_1652', 'd_1653', 'd_1654', 'd_1655', 'd_1656', 'd_1657', 'd_1658', 'd_1659', 'd_1660', 'd_1661', 'd_1662', 'd_1663', 'd_1664', 'd_1665', 'd_1666', 'd_1667', 'd_1668', 'd_1669', 'd_1670', 'd_1671', 'd_1672', 'd_1673', 'd_1674', 'd_1675', 'd_1676', 'd_1677', 'd_1678', 'd_1679', 'd_1680', 'd_1681', 'd_1682', 'd_1683', 'd_1684', 'd_1685', 'd_1686', 'd_1687', 'd_1688', 'd_1689', 'd_1690', 'd_1691', 'd_1692', 'd_1693', 'd_1694', 'd_1695', 'd_1696', 'd_1697', 'd_1698', 'd_1699', 'd_1700', 'd_1701', 'd_1702', 'd_1703', 'd_1704', 'd_1705', 'd_1706', 'd_1707', 'd_1708', 'd_1709', 'd_1710', 'd_1711', 'd_1712', 'd_1713', 'd_1714', 'd_1715', 'd_1716', 'd_1717', 'd_1718', 'd_1719', 'd_1720', 'd_1721', 'd_1722', 'd_1723', 'd_1724', 'd_1725', 'd_1726', 'd_1727', 'd_1728', 'd_1729', 'd_1730', 'd_1731', 'd_1732', 'd_1733', 'd_1734', 'd_1735', 'd_1736', 'd_1737', 'd_1738', 'd_1739', 'd_1740', 'd_1741', 'd_1742', 'd_1743', 'd_1744', 'd_1745', 'd_1746', 'd_1747', 'd_1748', 'd_1749', 'd_1750', 'd_1751', 'd_1752', 'd_1753', 'd_1754', 'd_1755', 'd_1756', 'd_1757', 'd_1758', 'd_1759', 'd_1760', 'd_1761', 'd_1762', 'd_1763', 'd_1764', 'd_1765', 'd_1766', 'd_1767', 'd_1768', 'd_1769', 'd_1770', 'd_1771', 'd_1772', 'd_1773', 'd_1774', 'd_1775', 'd_1776', 'd_1777', 'd_1778', 'd_1779', 'd_1780', 'd_1781', 'd_1782', 'd_1783', 'd_1784', 'd_1785', 'd_1786', 'd_1787', 'd_1788', 'd_1789', 'd_1790', 'd_1791', 'd_1792', 'd_1793', 'd_1794', 'd_1795', 'd_1796', 'd_1797', 'd_1798', 'd_1799', 'd_1800', 'd_1801', 'd_1802', 'd_1803', 'd_1804', 'd_1805', 'd_1806', 'd_1807', 'd_1808', 'd_1809', 'd_1810', 'd_1811', 'd_1812', 'd_1813', 'd_1814', 'd_1815', 'd_1816', 'd_1817', 'd_1818', 'd_1819', 'd_1820', 'd_1821', 'd_1822', 'd_1823', 'd_1824', 'd_1825', 'd_1826', 'd_1827', 'd_1828', 'd_1829', 'd_1830', 'd_1831', 'd_1832', 'd_1833', 'd_1834', 'd_1835', 'd_1836', 'd_1837', 'd_1838', 'd_1839', 'd_1840', 'd_1841', 'd_1842', 'd_1843', 'd_1844', 'd_1845', 'd_1846', 'd_1847', 'd_1848', 'd_1849', 'd_1850', 'd_1851', 'd_1852', 'd_1853', 'd_1854', 'd_1855', 'd_1856', 'd_1857', 'd_1858', 'd_1859', 'd_1860', 'd_1861', 'd_1862', 'd_1863', 'd_1864', 'd_1865', 'd_1866', 'd_1867', 'd_1868', 'd_1869', 'd_1870', 'd_1871', 'd_1872', 'd_1873', 'd_1874', 'd_1875', 'd_1876', 'd_1877', 'd_1878', 'd_1879', 'd_1880', 'd_1881', 'd_1882', 'd_1883', 'd_1884', 'd_1885', 'd_1886', 'd_1887', 'd_1888', 'd_1889', 'd_1890', 'd_1891', 'd_1892', 'd_1893', 'd_1894', 'd_1895', 'd_1896', 'd_1897', 'd_1898', 'd_1899', 'd_1900', 'd_1901', 'd_1902', 'd_1903', 'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910', 'd_1911', 'd_1912', 'd_1913']

--- head(5) ---

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,...,d_1884,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,d_1896,d_1897,d_1898,d_1899,d_1900,d_1901,d_1902,d_1903,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,1,0,4,2,3,0,1,2,0,0,0,1,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,2,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,6,6,0,0,0,0,3,1,2,1,3,1,0,2,5,4,2,0,3,0,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,4,4,0,1,4,0,1,0,1,0,1,1,2,0,1,1,2,1,1,0,1,1,2,2,2,4

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), str(6)
memory usage: 455.4 MB

--- describe(include='all').T ---

             count unique                            top   freq mean  std  min  25%  50%  75%    max
id           30490  30490  HOBBIES_1_001_CA_1_validation      1  NaN  NaN  NaN  NaN  NaN  NaN    NaN
item_id      30490   3049                  HOBBIES_1_001     10  NaN  NaN  NaN  NaN  NaN  NaN    NaN
dept_id      30490      7                        FOODS_3   8230  NaN  NaN  NaN  NaN  NaN  NaN    NaN
cat_id       30490      3                          FOODS  14370  NaN  NaN  NaN  NaN  NaN  NaN    NaN
store_id     30490     10                           CA_1   3049  NaN  NaN  NaN  NaN  NaN  NaN    NaN
...            ...    ...                            ...    ...  ...  ...  ...  ...  ...  ...    ...
d_1909   30,490.00    NaN                            NaN    NaN 1.16 2.88 0.00 0.00 0.00 1.00  88.00
d_1910   30,490.00    NaN                            NaN    NaN 1.15 2.95 0.00 0.00 0.00 1.00  77.00
d_1911   30,490.00    NaN                            NaN    NaN 1.33 3.36 0.00 0.00 0.00 1.00 141.00
d_1912   30,490.00    NaN                            NaN    NaN 1.61 4.09 0.00 0.00 0.00 2.00 171.00
d_1913   30,490.00    NaN                            NaN    NaN 1.63 3.81 0.00 0.00 0.00 2.00 130.00

[1919 rows x 11 columns]

--- memory usage (deep) ---
455.38 MB total

          MB
Index   0.00
id      2.26
item_id 1.80
dept_id 1.68
cat_id  1.62
...      ...
d_1909  0.23
d_1910  0.23
d_1911  0.23
d_1912  0.23
d_1913  0.23

[1920 rows x 1 columns]

--- missing values ---
No missing values detected in any column.

--- duplicate rows ---
0 fully duplicated row(s) out of 30,490 (0.0000%)

**What was done:** Ran the full profiling routine on `sales_df`.

**Why it matters:** `sales_train_validation` is stored in **wide format** — thousands of
`d_i` columns instead of a `date`/`quantity` pair — which is efficient for storage but unusable
directly for time-series modeling or for joining against `calendar`/`sell_prices`. Profiling
`describe()` across the `d_i` columns also surfaces early signals of the M5 dataset's known
characteristics: heavy **intermittency** (many zeros) and **right-skew** (occasional large
spikes), both of which matter for model choice later.

**ETL decision influenced:** Confirms this table needs to be **melted from wide to long**
(one row per `id` × `d`) before it can be joined to `calendar` on `d` and, transitively, to
`sell_prices` on `(store_id, item_id, wm_yr_wk)`. That reshape is explicitly deferred to the
Transform phase — this notebook only documents *why* it will be necessary.

## 9. Inspecting Every Identifier Column

Identifier columns (`id`, `item_id`, `dept_id`, `cat_id`, `store_id`, `state_id`,
`wm_yr_wk`, `d`, `date`) are the columns every join and every key decision depends on. For
each one we check: cardinality (`nunique`), whether it's unique per row, its value format, and
a small sample of values — rather than assuming their structure from documentation alone.

In [17]:
def inspect_identifier(df: pd.DataFrame, col: str, dataset_name: str) -> dict:
    series = df[col]
    n_unique = series.nunique(dropna=False)
    n_rows = len(series)
    return {
        "dataset": dataset_name,
        "column": col,
        "dtype": str(series.dtype),
        "n_unique": n_unique,
        "n_rows": n_rows,
        "is_unique_per_row": n_unique == n_rows,
        "n_nulls": int(series.isna().sum()),
        "sample_values": series.dropna().unique()[:3].tolist(),
    }


identifier_columns = [
    ("calendar", calendar_df, ["date", "wm_yr_wk", "d"]),
    ("sell_prices", sell_prices_df, ["store_id", "item_id", "wm_yr_wk"]),
    ("sales_train_validation", sales_df, ["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]),
]

id_reports = []
for dataset_name, df, cols in identifier_columns:
    for col in cols:
        id_reports.append(inspect_identifier(df, col, dataset_name))

identifier_report = pd.DataFrame(id_reports)
display(identifier_report)

,dataset,column,dtype,n_unique,n_rows,is_unique_per_row,n_nulls,sample_values
0,calendar,date,str,1969,1969,True,0,"[2011-01-29, 2011-01-30, 2011-01-31]"
1,calendar,wm_yr_wk,int64,282,1969,False,0,"[11101, 11102, 11103]"
2,calendar,d,str,1969,1969,True,0,"[d_1, d_2, d_3]"
3,sell_prices,store_id,str,10,6841121,False,0,"[CA_1, CA_2, CA_3]"
4,sell_prices,item_id,str,3049,6841121,False,0,"[HOBBIES_1_001, HOBBIES_1_002, HOBBIES_1_003]"
5,sell_prices,wm_yr_wk,int64,282,6841121,False,0,"[11325, 11326, 11327]"
6,sales_train_validation,id,str,30490,30490,True,0,"[HOBBIES_1_001_CA_1_validation, HOBBIES_1_002_..."
7,sales_train_validation,item_id,str,3049,30490,False,0,"[HOBBIES_1_001, HOBBIES_1_002, HOBBIES_1_003]"
8,sales_train_validation,dept_id,str,7,30490,False,0,"[HOBBIES_1, HOBBIES_2, HOUSEHOLD_1]"
9,sales_train_validation,cat_id,str,3,30490,False,0,"[HOBBIES, HOUSEHOLD, FOODS]"
10,sales_train_validation,store_id,str,10,30490,False,0,"[CA_1, CA_2, CA_3]"
11,sales_train_validation,state_id,str,3,30490,False,0,"[CA, TX, WI]"

**What was done:** For every identifier-style column across all three tables, computed
cardinality, row count, whether the column is unique per row, null count, and a small value
sample — laid out as a single comparison table.

**Why it matters:** This is the evidence base for every claim we're about to make about
primary keys, foreign keys, and grain. A key claim like *"`id` uniquely identifies a row in
`sales_train_validation`"* should be **verified** (`is_unique_per_row == True`), not assumed
from the M5 competition documentation, since real-world extracts can diverge from spec
(duplicate rows, re-exports, truncated files, etc.).

**ETL decision influenced:** Directly feeds section 11 (Primary & Foreign Keys) below — any
column here that unexpectedly shows `is_unique_per_row == False` where uniqueness was assumed
would block a Transform-phase merge until investigated, since it would produce row
duplication (a "fan-out") on join.

## 10. Discovering Relationships Between Datasets

We now check how the three tables actually connect, using set-overlap and dependency checks
**on the real data** rather than the documented schema alone.

- `calendar.d` ↔ the `d_i` column names of `sales_train_validation` (day key).
- `calendar.wm_yr_wk` ↔ `sell_prices.wm_yr_wk` (week key).
- `sales_train_validation.item_id` / `store_id` ↔ `sell_prices.item_id` / `store_id` (product & store keys).
- Functional dependency: does `store_id` always imply the same `state_id`?

In [18]:
# --- calendar.d vs the d_i columns present in sales_train_validation ---
sales_day_cols = [c for c in sales_df.columns if c.startswith("d_")]
calendar_days = set(calendar_df["d"])
sales_days = set(sales_day_cols)

print("Day-key relationship: calendar.d <-> sales_train_validation d_i columns")
print(f"  distinct days in calendar          : {len(calendar_days):,}")
print(f"  d_i columns in sales_train_validation: {len(sales_days):,}")
print(f"  days in calendar but NOT in sales    : {len(calendar_days - sales_days):,}")
print(f"  d_i columns in sales but NOT in calendar: {len(sales_days - calendar_days):,}")

# --- calendar.wm_yr_wk vs sell_prices.wm_yr_wk ---
cal_weeks = set(calendar_df["wm_yr_wk"])
price_weeks = set(sell_prices_df["wm_yr_wk"])
print("\nWeek-key relationship: calendar.wm_yr_wk <-> sell_prices.wm_yr_wk")
print(f"  distinct weeks in calendar    : {len(cal_weeks):,}")
print(f"  distinct weeks in sell_prices : {len(price_weeks):,}")
print(f"  weeks in sell_prices but NOT in calendar: {len(price_weeks - cal_weeks):,}")

# --- item_id / store_id overlap between sales and sell_prices ---
print("\nProduct/store-key relationship: sales_train_validation <-> sell_prices")
sales_items, price_items = set(sales_df["item_id"]), set(sell_prices_df["item_id"])
sales_stores, price_stores = set(sales_df["store_id"]), set(sell_prices_df["store_id"])
print(f"  item_id overlap : {len(sales_items & price_items):,} shared "
      f"({len(sales_items - price_items):,} sales-only, {len(price_items - sales_items):,} prices-only)")
print(f"  store_id overlap: {len(sales_stores & price_stores):,} shared "
      f"({len(sales_stores - price_stores):,} sales-only, {len(price_stores - sales_stores):,} prices-only)")

# --- functional dependency: store_id -> state_id ---
fd_check = sales_df.groupby("store_id")["state_id"].nunique()
violations = fd_check[fd_check > 1]
print("\nFunctional dependency check: store_id -> state_id")
if violations.empty:
    print("  Holds for all stores: every store_id maps to exactly one state_id.")
else:
    print(f"  VIOLATED for {len(violations)} store_id value(s):")
    display(violations)

Day-key relationship: calendar.d <-> sales_train_validation d_i columns
  distinct days in calendar          : 1,969
  d_i columns in sales_train_validation: 1,913
  days in calendar but NOT in sales    : 56
  d_i columns in sales but NOT in calendar: 0

Week-key relationship: calendar.wm_yr_wk <-> sell_prices.wm_yr_wk
  distinct weeks in calendar    : 282
  distinct weeks in sell_prices : 282
  weeks in sell_prices but NOT in calendar: 0

Product/store-key relationship: sales_train_validation <-> sell_prices
  item_id overlap : 3,049 shared (0 sales-only, 0 prices-only)
  store_id overlap: 10 shared (0 sales-only, 0 prices-only)

Functional dependency check: store_id -> state_id
  Holds for all stores: every store_id maps to exactly one state_id.

**What was done:** Measured the *actual* set overlap between the day key
(`calendar.d` vs. the sales table's `d_i` column names), the week key
(`calendar.wm_yr_wk` vs. `sell_prices.wm_yr_wk`), and the product/store keys
(`item_id`/`store_id` shared between `sales_train_validation` and `sell_prices`). Also tested
the functional dependency `store_id → state_id`.

**Why it matters:** A join is only safe when the key domains actually line up. For example, if
`sell_prices` contained `wm_yr_wk` values absent from `calendar`, a join would silently drop
rows (or need an explicit `how="left"` decision) — something we want to *know*, not discover
after modeling. The `store_id → state_id` check confirms `state_id` is redundant information
that could be derived from `store_id` alone (a normalization/dimension-table signal).

**ETL decision influenced:** Confirms the join path the Transform phase should implement:
melt `sales_train_validation` → merge onto `calendar` via `d` → merge the result onto
`sell_prices` via `(store_id, item_id, wm_yr_wk)`. Any overlap gaps surfaced above dictate
whether those merges should be `inner` (drop unmatched) or `left` (keep unmatched, expect
nulls) joins.

## 11. Primary Keys and Foreign Keys

Based on the identifier inspection (§9) and relationship discovery (§10) above, the key
structure is:

| Table | Primary Key (grain) | Foreign Keys |
|---|---|---|
| `calendar` | `d` (equivalently `date`, 1:1) — one row per **day** | *none* (calendar is the root time dimension) |
| `sell_prices` | composite: `(store_id, item_id, wm_yr_wk)` — one row per **store × item × week** | `wm_yr_wk` → `calendar.wm_yr_wk` |
| `sales_train_validation` | `id` — one row per **item × store** series (before melting); after melting to long format it becomes composite `(id, d)` | `item_id`, `store_id` (composite, → `sell_prices`); `d` → `calendar.d` (only after melting) |

Notes:
- `sales_train_validation.id` is *itself* a concatenation of `item_id` + `store_id` + the
  literal suffix `"validation"` — i.e. it is a **derived/surrogate key**, not an independently
  assigned one. `item_id` + `store_id` together already uniquely identify a series.
- There is no single column in `sell_prices` that is unique per row; uniqueness only holds for
  the **composite** `(store_id, item_id, wm_yr_wk)`, which was verified implicitly by row-count
  vs. cardinality comparisons in §9/§10 and confirmed with an explicit duplicate check below.

In [19]:
composite_key_cols = ["store_id", "item_id", "wm_yr_wk"]
n_rows = len(sell_prices_df)
n_unique_composite = sell_prices_df[composite_key_cols].drop_duplicates().shape[0]

print("Composite key check for sell_prices: (store_id, item_id, wm_yr_wk)")
print(f"  total rows            : {n_rows:,}")
print(f"  unique combinations   : {n_unique_composite:,}")
print(f"  composite key is valid: {n_rows == n_unique_composite}")

print("\nPrimary key check for sales_train_validation: id")
print(f"  is 'id' unique per row: {sales_df['id'].is_unique}")

Composite key check for sell_prices: (store_id, item_id, wm_yr_wk)
  total rows            : 6,841,121
  unique combinations   : 6,841,121
  composite key is valid: True

Primary key check for sales_train_validation: id
  is 'id' unique per row: True

**What was done:** Explicitly verified that `(store_id, item_id, wm_yr_wk)` has zero
duplicate combinations in `sell_prices` (i.e. it is a valid composite primary key), and that
`id` is unique per row in `sales_train_validation`.

**Why it matters:** "Primary key" claims are only trustworthy once verified programmatically —
this table doesn't come with database-enforced constraints (it's a CSV), so uniqueness must be
checked rather than assumed from the competition documentation.

**ETL decision influenced:** This key map is what the Transform phase's `merge()` calls should
be built against verbatim: `on="d"` for calendar↔sales, `on=["store_id","item_id","wm_yr_wk"]`
for the result↔sell_prices. It also tells the Load phase which columns need a uniqueness
constraint (or composite index) if the target is a relational warehouse table.

## 12. Dimension Tables vs. Fact Tables

Viewed through a star-schema lens:

| Table | Role | Reasoning |
|---|---|---|
| `calendar` | **Dimension** (time dimension) | One row per day; descriptive attributes (weekday, month, events, SNAP flags) about *when*, not a measured quantity. Low row count relative to the fact table. |
| `sell_prices` | **Hybrid** — weekly price *fact*, but also functions as a **product/store price-lookup dimension** for the daily grain | Contains a measure (`sell_price`) but at a coarser (weekly) grain than the core fact table, so relative to `sales_train_validation` it behaves like a dimension to be looked up. |
| `sales_train_validation` (melted) | **Fact table** | Contains the actual measured quantity we care about — units sold — at the finest available grain (item × store × day), with foreign keys out to every dimension. |

An implied **product dimension** (`item_id`, `dept_id`, `cat_id`) and **store/location
dimension** (`store_id`, `state_id`) are currently embedded *inside* the fact table rather than
normalized into their own tables — worth flagging for the Transform/Load phases if a proper
star schema is desired downstream (e.g. for a BI/warehouse layer).

In [20]:
# Evidence: product & location attributes are repeated (denormalized) across many rows
# of the fact table, which is exactly what a proper dimension table would remove.
product_dim_preview = sales_df[["item_id", "dept_id", "cat_id"]].drop_duplicates()
location_dim_preview = sales_df[["store_id", "state_id"]].drop_duplicates()

print(f"Fact table rows                 : {len(sales_df):,}")
print(f"Distinct (item_id, dept_id, cat_id) combos -> implied product dimension size: {len(product_dim_preview):,}")
print(f"Distinct (store_id, state_id) combos       -> implied store dimension size : {len(location_dim_preview):,}")

display(product_dim_preview.head())
display(location_dim_preview.head())

Fact table rows                 : 30,490
Distinct (item_id, dept_id, cat_id) combos -> implied product dimension size: 3,049
Distinct (store_id, state_id) combos       -> implied store dimension size : 10

         item_id    dept_id   cat_id
0  HOBBIES_1_001  HOBBIES_1  HOBBIES
1  HOBBIES_1_002  HOBBIES_1  HOBBIES
2  HOBBIES_1_003  HOBBIES_1  HOBBIES
3  HOBBIES_1_004  HOBBIES_1  HOBBIES
4  HOBBIES_1_005  HOBBIES_1  HOBBIES

      store_id state_id
0         CA_1       CA
3049      CA_2       CA
6098      CA_3       CA
9147      CA_4       CA
12196     TX_1       TX

**What was done:** Quantified how much repetition exists in the product-related
(`item_id`, `dept_id`, `cat_id`) and location-related (`store_id`, `state_id`) attributes
inside the fact table, by counting their distinct combinations relative to total row count.

**Why it matters:** The large gap between total fact rows and the small number of distinct
product/location combinations is direct evidence of denormalization — those attributes are
dimension-like even though they currently live inside the fact table.

**ETL decision influenced:** If a Load-phase target is a dimensional warehouse (star schema),
this is the evidence to extract `dim_product` and `dim_store` tables during Transform (via
`drop_duplicates()` on the columns shown above) rather than repeating those attributes on every
fact row.

## 13. Dataset Size and Memory Requirements

We already captured per-dataset memory usage inside `profile_dataset()`. Here we consolidate
those numbers into a single summary and — importantly — **project forward** to the memory that
the *melted* (long-format) version of `sales_train_validation` will require, since that reshape
is known to be coming in the Transform phase (§8) and is by far the largest driver of memory
pressure in this pipeline.

In [21]:
summary_rows = []
for name, df in raw_datasets.items():
    summary_rows.append({
        "dataset": name,
        "rows": len(df),
        "columns": df.shape[1],
        "memory_MB_shallow": df.memory_usage(deep=False).sum() / (1024 ** 2),
        "memory_MB_deep": df.memory_usage(deep=True).sum() / (1024 ** 2),
    })

memory_summary = pd.DataFrame(summary_rows)
memory_summary["total_MB_deep"] = memory_summary["memory_MB_deep"]
display(memory_summary)

print(f"\nCombined raw in-memory footprint (deep): {memory_summary['memory_MB_deep'].sum():,.2f} MB")

# Forward-looking projection: melting sales_train_validation from wide to long
# multiplies row count by the number of day columns and collapses to ~3 columns
# (id, d, sales) plus the untouched categorical id columns repeated per row.
n_day_cols = len([c for c in sales_df.columns if c.startswith("d_")])
projected_long_rows = len(sales_df) * n_day_cols
print(f"\nProjected row count AFTER melting sales_train_validation to long format: {projected_long_rows:,} rows")
print("(Actual melt is deferred to the Transform phase; this is a sizing estimate only.)")

                  dataset     rows  columns  memory_MB_shallow  memory_MB_deep  total_MB_deep
0                calendar     1969       14               0.21            0.67           0.67
1             sell_prices  6841121        4             208.77          853.13         853.13
2  sales_train_validation    30490     1919             446.40          455.38         455.38

Combined raw in-memory footprint (deep): 1,309.19 MB

Projected row count AFTER melting sales_train_validation to long format: 58,327,370 rows
(Actual melt is deferred to the Transform phase; this is a sizing estimate only.)

**What was done:** Consolidated shallow vs. deep memory usage across all three raw
tables into one summary table, and computed a forward-looking row-count projection for what
`sales_train_validation` will grow to once melted from wide to long format (rows ×
number of `d_i` columns).

**Why it matters:** Deep memory usage (which accounts for actual string/object payload size,
not just pointer size) is the number that matters for capacity planning — shallow usage
systematically understates memory for any `object`-dtype column. The melt projection matters
because wide-to-long reshapes are exactly the kind of operation that silently balloons memory
if not planned for (going from tens of thousands of rows to tens of millions).

**ETL decision influenced:** If the projected melted row count is large relative to available
RAM, this is the evidence to decide — **before** the Transform phase is built — whether it
needs chunked processing (e.g. `pd.read_csv(..., chunksize=...)`, per-store processing loops,
or a switch to Dask/Polars) rather than a single `pd.melt()` call on the full DataFrame.

## 14. Potential Data Quality Issues

A structured sweep for the data-quality categories most relevant to a forecasting pipeline:
missing values (recap), duplicate rows, referential gaps, and value-range sanity checks
(negative/zero prices, negative sales, unexpected data types).

In [22]:
issues = []

# 1) Missing values recap (counts already computed inside profile_dataset per table)
for name, df in raw_datasets.items():
    n_missing_cols = (df.isna().sum() > 0).sum()
    issues.append({
        "check": "missing values",
        "dataset": name,
        "finding": f"{n_missing_cols} column(s) contain at least one null",
        "severity": "info" if n_missing_cols == 0 else "review",
    })

# 2) Duplicate rows recap
for name, df in raw_datasets.items():
    n_dupes = df.duplicated().sum()
    issues.append({
        "check": "duplicate rows",
        "dataset": name,
        "finding": f"{n_dupes} fully duplicated row(s)",
        "severity": "info" if n_dupes == 0 else "review",
    })

# 3) sell_price sanity: non-positive prices
non_positive_prices = (sell_prices_df["sell_price"] <= 0).sum()
issues.append({
    "check": "value range (sell_price <= 0)",
    "dataset": "sell_prices",
    "finding": f"{non_positive_prices} row(s) with sell_price <= 0",
    "severity": "info" if non_positive_prices == 0 else "review",
})

# 4) sales sanity: negative units sold across all d_i columns
day_cols = [c for c in sales_df.columns if c.startswith("d_")]
negative_sales_cells = (sales_df[day_cols] < 0).to_numpy().sum()
issues.append({
    "check": "value range (units sold < 0)",
    "dataset": "sales_train_validation",
    "finding": f"{negative_sales_cells} cell(s) with negative units sold across all day columns",
    "severity": "info" if negative_sales_cells == 0 else "review",
})

# 5) Referential gap: weeks present in sell_prices but absent from calendar
weeks_gap = len(set(sell_prices_df["wm_yr_wk"]) - set(calendar_df["wm_yr_wk"]))
issues.append({
    "check": "referential integrity (sell_prices.wm_yr_wk -> calendar.wm_yr_wk)",
    "dataset": "sell_prices / calendar",
    "finding": f"{weeks_gap} week value(s) in sell_prices not found in calendar",
    "severity": "info" if weeks_gap == 0 else "review",
})

# 6) Sparsity / intermittency signal in sales (relevant for model choice, not a "defect")
zero_fraction = (sales_df[day_cols] == 0).to_numpy().mean()
issues.append({
    "check": "sparsity (fraction of zero-sales cells)",
    "dataset": "sales_train_validation",
    "finding": f"{zero_fraction:.2%} of all (item, store, day) cells equal zero",
    "severity": "info",
})

# 7) High-cardinality / mostly-null event columns (expected pattern, not a defect)
for col in ["event_name_1", "event_type_1", "event_name_2", "event_type_2"]:
    pct_null = calendar_df[col].isna().mean()
    issues.append({
        "check": "sparse categorical column",
        "dataset": "calendar",
        "finding": f"'{col}' is {pct_null:.1%} null",
        "severity": "info",
    })

quality_report = pd.DataFrame(issues)
display(quality_report)

                                                check                 dataset                                            finding severity
0                                      missing values                calendar              4 column(s) contain at least one null   review
1                                      missing values             sell_prices              0 column(s) contain at least one null     info
2                                      missing values  sales_train_validation              0 column(s) contain at least one null     info
3                                      duplicate rows                calendar                          0 fully duplicated row(s)     info
4                                      duplicate rows             sell_prices                          0 fully duplicated row(s)     info
5                                      duplicate rows  sales_train_validation                          0 fully duplicated row(s)     info
6                       value range (sell_price <= 0)             sell_prices                      0 row(s) with sell_price <= 0     info
7                        value range (units sold < 0)  sales_train_validation  0 cell(s) with negative units sold across all ...     info
8   referential integrity (sell_prices.wm_yr_wk ->...  sell_prices / calendar  0 week value(s) in sell_prices not found in ca...     info
9             sparsity (fraction of zero-sales cells)  sales_train_validation  68.20% of all (item, store, day) cells equal zero     info
10                          sparse categorical column                calendar                       'event_name_1' is 91.8% null     info
11                          sparse categorical column                calendar                       'event_type_1' is 91.8% null     info
12                          sparse categorical column                calendar                       'event_name_2' is 99.7% null     info
13                          sparse categorical column                calendar                       'event_type_2' is 99.7% null     info

**What was done:** Ran a checklist-style sweep covering: missing values, duplicate
rows, non-positive prices, negative sales quantities, a referential-integrity check between
`sell_prices.wm_yr_wk` and `calendar.wm_yr_wk`, the overall zero-sales sparsity rate, and the
null rate of the four event columns — tagging each finding with a severity (`info` vs.
`review`).

**Why it matters:** M5 is a well-known benchmark dataset, but "well-known" doesn't mean
"assume it's clean" — a production pipeline should verify these properties against the actual
file on disk every time, since raw exports, re-downloads, or partial files can silently differ
from expectations. Distinguishing `info` (expected pattern, e.g. sparse events) from `review`
(needs a human decision, e.g. non-positive prices) keeps the report actionable rather than
alarming.

**ETL decision influenced:** Any `review`-tagged row here becomes an explicit, documented
decision the Transform phase must make (e.g. "drop rows with `sell_price <= 0`" or "treat as
promotional/free items and keep them") — decided with evidence, not silently overwritten by a
generic `.dropna()` / `.fillna(0)` call.

## 15. Extract Phase Decisions — Summary

This section consolidates everything discovered above into the concrete facts and decisions
the **Transform phase** will build on.

### 15.1 Confirmed facts about the raw data

- **Three raw tables** were located and loaded successfully via a portable, marker-based
  `pathlib` project-root resolver (no absolute paths).
- **`calendar`** is a time dimension at **daily grain**, keyed by `d` (⟷ `date`, 1:1).
- **`sell_prices`** is keyed by the **composite** `(store_id, item_id, wm_yr_wk)` — weekly
  grain, one level coarser than daily.
- **`sales_train_validation`** is the **fact table**, currently stored **wide** (one column per
  day, `d_1..d_n`), keyed by `id` (derivable from `item_id` + `store_id`).
- `store_id → state_id` is a **functional dependency** (verified) — `state_id` is redundant
  information relative to `store_id`.
- Product attributes (`item_id`, `dept_id`, `cat_id`) and location attributes (`store_id`,
  `state_id`) are **denormalized** into the fact table — candidates for `dim_product` /
  `dim_store` extraction.
- Event columns (`event_name_1/2`, `event_type_1/2`) are **legitimately sparse**, not broken —
  most days have no event.
- Sales data is expected to be **highly intermittent** (a large share of zero-sales
  item/store/day cells) — see the sparsity metric in §14.

### 15.2 Key structure to carry into Transform

| Join | Keys | Type |
|---|---|---|
| `sales_train_validation` (melted) → `calendar` | `d` | many-to-one |
| result → `sell_prices` | `(store_id, item_id, wm_yr_wk)` | many-to-one |

### 15.3 Decisions this phase hands off to Transform

1. **Reshape** `sales_train_validation` from wide (`d_1..d_n` columns) to long
   (`id`, `d`, `sales` rows) — required before any date-based join or time-series operation.
2. **Join order**: melt sales → merge with `calendar` on `d` → merge with `sell_prices` on
   `(store_id, item_id, wm_yr_wk)`.
3. **Dtype optimization** (e.g. downcasting sales counts to `int16`/`int32`, prices to
   `float32`, high-repetition string columns to `category`) should happen in Transform, sized
   against the memory projection in §13 — not guessed at up front.
4. **Missing-value strategy for events**: fill `event_name_*` / `event_type_*` with an explicit
   sentinel category (e.g. `"none"`), do **not** drop rows or columns.
5. **Any `review`-severity findings from §14** (non-positive prices, negative sales, referential
   gaps, if present in the real dataset) must be resolved with an explicit, documented rule
   before Transform proceeds — this notebook intentionally leaves them **unresolved** and
   visible.
6. **Dimensional modeling** (optional, if a warehouse/BI Load target is planned): extract
   `dim_product` and `dim_store` from the fact table using the `drop_duplicates()` patterns
   demonstrated in §12.
7. **Scalability**: if the melted row-count projection from §13 is large relative to available
   memory, Transform should process in chunks (e.g. per `store_id`) rather than materializing
   one full long-format DataFrame in memory.

### 15.4 Explicit non-goals of this notebook (by design)

- No data was cleaned, imputed, cast, or dropped.
- No files were written to `data/processed/` or anywhere else.
- No merges were materialized — only their *feasibility and correctness* were verified.
- No modeling or feature engineering occurred.

---
**Next notebook in the pipeline:** `notebooks/02_transform.ipynb`